### ISSUE TITLE
Right-Click Start DeadLock in Administrator Mode

### ISSUE THREAD

**Issue by Bamajon1974** [CodeDead/DeadLock#15]
When unlocking a file(s) or folder(s) by right clicking on the item, how does one run DeadLock in Administrator mode? There is only an option to turn on and off administrator warning in the settings but I see no option to restart DeadLock as an Admin. Thanks!

**Comment by CodeDead** [comment]
HI @Bamajon1974 ,

You can solve this problem by navigating to:
`C:\Program Files (x86)\CodeDead\DeadLock` and right clicking on the `DeadLock.exe` file which should be located there or in the location you've installed DeadLock.

After which, select the option to open the file properties and navigate to the 'Compatibility` section in the dialog that pops up.
From there, you should find the option to automatically run DeadLock as an administrator.
![Screenshot from 2020-09-23 13-55-18](https://user-images.githubusercontent.com/16293330/94009876-5d999980-fda5-11ea-961b-a35c2760d282.png)

Hopefully this helps!

**Comment by Bamajon1974** [comment]
Great. Thank you. I don't know why I didn't remember to do that.

Are you planning on updating DeadLock and releasing a new version soon? If
so, can you add options in settings to restart as admin or permanently load
as admin?

Thanks, Jon

**Comment by CodeDead** [comment]
Hi @Bamajon1974 ,

We're currently in the process of upgrading [our website](http://dev.codedead.com/). After that we'll carry on updating our software as per usual.
DeadLock hasn't been updated in quite a while and maybe it's time to get back into it. Thank you for the suggestion, it will definitely be on the todo list in the future!

Kind regards

**Comment by Bamajon1974** [comment]
Great! Please let me know when you update Deadlock.
Thanks, Jon
